spring:
  application:
    name: pinecone
  profiles:
    active: dev
  messages:
    basename: i18n/messages


gcp:
  project:
    id: work-places-2f42a
  bucket:
    id: work-places-2f42a.appspot.com
  config:
    file: gcp-account-file.json
  dir:
    name: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html



server:
  port: 8080